ToDoList/Models/Category.cs
using System.Collections.Generic;

namespace ToDoList.Models
{
    public class Category
    {
        public Category()
        {
            this.Items = new HashSet<Item>(); //A HashSet is an unordered collection of unique elements. We create a HashSet of Items in the constructor to help avoid exceptions when no records exist in the "many" side of the relationship.
        }

        public int CategoryId { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Item> Items { get; set; } //We declare Items as an instance of ICollection, a generic interface built into the .NET framework. We use ICollection specifically because Entity requires it.
    }
}

ToDoList/Models/Item.cs
namespace ToDoList.Models
{
    public class Item
    {
        public int ItemId { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }
    }
}

ToDoList/Models/ToDoListContext.cs
using Microsoft.EntityFrameworkCore;

namespace ToDoList.Models
{
  public class ToDoListContext : DbContext
  {
    public virtual DbSet<Category> Categories { get; set; } 
    public DbSet<Item> Items { get; set; }

    public ToDoListContext(DbContextOptions options) : base(options) { }
  }
}

ToDoList/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace ToDoList.Controllers
{
  public class CategoriesController : Controller
  {
    private readonly ToDoListContext _db;

    public CategoriesController(ToDoListContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Category> model = _db.Categories.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Category category)
    {
      _db.Categories.Add(category);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Category thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
      return View(thisCategory);
    }

    public ActionResult Edit(int id)
    {
      var thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
      return View(thisCategory);
    }

    [HttpPost]
    public ActionResult Edit(Category category)
    {
      _db.Entry(category).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
      return View(thisCategory);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCategory = _db.Categories.FirstOrDefault(category => category.CategoryId == id);
      _db.Categories.Remove(thisCategory);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

ToDoList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ToDoList.Controllers
{
  public class HomeController : Controller
  {

    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }

  }
}

ToDoList/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ToDoList.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ToDoListContext _db;

        public ItemsController(ToDoListContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Item> model = _db.Items.Include(items => items.Category).ToList(); //We can utilize eager loading by using Entity's built-in Include() methodThis basically states the following: for each Item in the database, include the Category it belongs to and then put all the Items into list.
            return View(model);
        }


        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Item item)
        {
            _db.Items.Add(item);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Item thisItem = _db.Items.FirstOrDefault(items => items.ItemId == id);
            //^This is our way of communicating to the database, giving it the id that was passed in and telling the database to give us the item in the database that has this id. In this line, "items" is not a special name.
            return View(thisItem);
        }
        public ActionResult Edit(int id)
        {
            var thisItem = _db.Items.FirstOrDefault(items => items.ItemId == id);
            ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
            return View(thisItem);
        }

        [HttpPost]
        public ActionResult Edit(Item item)
        {
            _db.Entry(item).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            var thisItem = _db.Items.FirstOrDefault(items => items.ItemId == id);
            return View(thisItem);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisItem = _db.Items.FirstOrDefault(items => items.ItemId == id);
            _db.Items.Remove(thisItem);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

ToDoList/Views/Categories/Create.cshtml
@model ToDoList.Models.Category

<h4>Add a new category</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <input type="submit" value="Add new category" />
}
<p>@Html.ActionLink("Show all categories", "Index")</p>

ToDoList/Views/Categories/Edit.cshtml
@model ToDoList.Models.Category

<h2>Edit</h2>

<h4>Edit this category: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.CategoryId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to categories", "Index")</p>

ToDoList/Views/Categories/Index.cshtml
@using ToDoList.Models;
@model List<ToDoList.Models.Category>;

<h1>Categories</h1>

@if (@Model.Count == 0)
{
  <h3>No categories have been added yet!</h3>
} 

@foreach (Category category in Model)
{
  <li>@Html.ActionLink($"{category.Name}", "Details", new { id = category.CategoryId })</li>
}

<p>@Html.ActionLink("Add new category", "Create")</p>

<p>@Html.ActionLink("Home", "Index", "Home")</p>

ToDoList/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>To Do List</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link href="~/css/styles.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
    <h1>Welcome to the To Do List!</h1>
    <p>@Html.ActionLink("See all items", "Index", "Items")</p> 
    <!-- ^When we click on "see all items", it will take us to the Index method in our Items controller -->
    <p>@Html.ActionLink("See all categories", "Index", "Categories")</p>
    </div>
</body>
</html>

ToDoList/Views/Items/Create.cshtml
@model ToDoList.Models.Item
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>To Do List</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link href="~/css/styles.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
        <h4>Add a new task</h4>
        @using (Html.BeginForm())
        {
            @Html.LabelFor(model => model.Description)
            @Html.TextBoxFor(model => model.Description)

            @Html.LabelFor(model => model.Category)
            @Html.DropDownList("CategoryId") 
            <!-- ^corresponds to the name attribute of the dropdown list -->

            <input type="submit" value="Add new item" class="btn btn-default" />
        }

        <p>@Html.ActionLink("Show all items", "Index")</p>
    </div>
</body>
</html>

ToDoList/Views/Items/Delete.cshtml
@model ToDoList.Models.Item

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

ToDoList/Views/Items/Details.cshtml
@model ToDoList.Models.Item
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>To Do List</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link href="~/css/styles.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
    <h2>Item Details</h2>
    <hr />
    <h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)<h3>
    <p>@Html.ActionLink("Back to list", "Index")</p>
    <p>@Html.ActionLink("Edit Item", "Edit", new { id = Model.ItemId })</p>
    <p>@Html.ActionLink("Delete Item", "Delete", new { id = Model.ItemId })</p>
    </div>
</body>
</html>

ToDoList/Views/Items/Edit.cshtml
@model ToDoList.Models.Item

<h2>Edit</h2>

<h4>Edit this task: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ItemId) 
    //This is because we need to pass the specific item's ItemId on to the controller

    @Html.LabelFor(model => model.Description)
    @Html.EditorFor(model => model.Description)

    @Html.LabelFor(model => model.Category)
    @Html.DropDownList("CategoryId")

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

ToDoList/Views/Items/Index.cshtml
@using ToDoList.Models;
@model List<ToDoList.Models.Item>;
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>To Do List</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link href="~/css/styles.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
        <h1>Items</h1>

        @if (@Model.Count == 0)
        {
        <h3>No items have been added yet!</h3>
        } 

        <ul>
            @foreach (Item item in Model)
            {
              <li>@Html.ActionLink($"{item.Description}", "Details", new { id = item.ItemId }) | @item.Category.Name</li>
            }
        </ul>
        
        <p>@Html.ActionLink("Add new item", "Create")</p>
        <p>@Html.ActionLink("Home", "Index", "Home")</p>
    </div>
</body>
</html>

ToDoList/Views/Items/Show.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Parcels</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link href="~/css/styles.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="container">
<h1>To Do List Item Details: </h1>

<h2>@Model["item"].Description</h2>
<h3>Category: @Model["category"].Name</h3>

<a href='/categories/@Model["category"].Id/items/new'>Add another item</a>
<a href='/categories'>View all categories</a>
</div>
</body>
</html>